global:
  scrape_interval: 5s # Intervalo de recoleccion de métricas

scrape_configs:
  - job_name: 'infraestructura-docker'
    static_configs:
      - targets: ['cadvisor:8080'] # Endpoint de cAdvisor para la telemetría de los contenedores