[project]
name = "Proyecto-Templates-IT"
version = "1.0.0"
description = "Centralización de instructivos para el equipo de Soporte IT . Web estatica minimalista para el copiado y pegado rapido."
readme = "README.md"
authors = [
    { name = "Jonathan Sotelo", email = "thomas.sotelo18@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.30.0",
]

[project.urls]
Homepage = "https://github.com/thomassotelo7/Proyecto-Templates-IT"